[
    "CSAT (Pacific)",
    east,
    [
        "O_T_Soldier_F",
        "O_T_Soldier_LAT_F",
        "O_T_Soldier_GL_F",
        "O_T_Soldier_AR_F",
        "O_T_Soldier_AAR_F",
        "O_T_Soldier_TL_F",
        "O_T_Soldier_SL_F",
        "O_T_Soldier_M_F",
        "O_T_Soldier_A_F",
        "O_T_Medic_F",
        "O_T_Engineer_F",
        "O_T_Soldier_Exp_F",
        "O_T_Soldier_AT_F",
        "O_T_Soldier_AAT_F",
        "O_T_sniper_F",
        "O_T_spotter_F",
        "O_T_Soldier_Repair_F",
        "O_T_Soldier_PG_F",
        "O_T_Helipilot_F",
        "O_T_helicrew_F",
        "O_T_Crew_F",
        "O_T_officer_F",
        "O_T_soldier_UAV_F"
    ],
    [
        "O_T_Quadbike_01_ghex_F",
        "O_T_MRAP_02_ghex_F",
        "O_T_MRAP_02_hmg_ghex_F",
        "O_T_MRAP_02_gmg_ghex_F",
        "O_T_Truck_03_transport_ghex_F",
        "O_T_Truck_03_covered_ghex_F",
        "O_T_Truck_03_device_ghex_F",
        "O_T_APC_Wheeled_02_rcws_ghex_F",
        "O_T_APC_Tracked_02_cannon_ghex_F",
        "O_T_APC_Tracked_02_AA_ghex_F",
        "O_T_MBT_02_cannon_ghex_F",
        "O_T_MBT_02_arty_ghex_F"
    ],
    [
        "O_UAV_02_F",
        "O_UAV_02_CAS_F",
        "O_UAV_01_F",
        "O_UGV_01_F",
        "O_UGV_01_rcws_F",
        "O_Heli_Light_02_unarmed_F",
        "O_Heli_Light_02_F",
        "O_Heli_Attack_02_black_F",
        "O_T_VTOL_02_infantry_F",
        "O_T_VTOL_02_vehicle_F",
        "O_Plane_CAS_02_F"
    ],
    [
        "O_HMG_01_F",
        "O_HMG_01_high_F",
        "O_GMG_01_F",
        "O_GMG_01_high_F",
        "O_static_AT_F",
        "O_static_AA_F",
        "O_Mortar_01_F"
    ],
    [
        "O_Boat_Armed_01_hmg_F",
        "O_Boat_Transport_01_F"
    ]
]
