[
    "CSAT (Eastern)",
    east,
    [
        "O_Soldier_F",
        "O_Soldier_LAT_F",
        "O_Soldier_GL_F",
        "O_Soldier_AR_F",
        "O_Soldier_AAR_F",
        "O_Soldier_TL_F",
        "O_Soldier_SL_F",
        "O_Soldier_M_F",
        "O_Soldier_A_F",
        "O_medic_F",
        "O_engineer_F",
        "O_soldier_exp_F",
        "O_Soldier_AT_F",
        "O_Soldier_AAT_F",
        "O_sniper_F",
        "O_spotter_F",
        "O_soldier_repair_F",
        "O_soldier_PG_F",
        "O_helipilot_F",
        "O_helicrew_F",
        "O_crew_F",
        "O_officer_F",
        "O_soldier_UAV_F"
    ],
    [
        "O_Quadbike_01_F",
        "O_MRAP_02_F",
        "O_MRAP_02_hmg_F",
        "O_MRAP_02_gmg_F",
        "O_Truck_03_transport_F",
        "O_Truck_03_covered_F",
        "O_Truck_03_device_F",
        "O_APC_Wheeled_02_rcws_F",
        "O_APC_Tracked_02_cannon_F",
        "O_APC_Tracked_02_AA_F",
        "O_MBT_02_cannon_F",
        "O_MBT_02_arty_F"
    ],
    [
        "O_UAV_02_F",
        "O_UAV_02_CAS_F",
        "O_UAV_01_F",
        "O_UGV_01_F",
        "O_UGV_01_rcws_F",
        "O_Heli_Light_02_unarmed_F",
        "O_Heli_Light_02_F",
        "O_Heli_Attack_02_F",
        "O_Heli_Transport_04_bench_F",
        "O_Heli_Transport_04_covered_F",
        "O_Plane_CAS_02_F"
    ],
    [
        "O_HMG_01_F",
        "O_HMG_01_high_F",
        "O_GMG_01_F",
        "O_GMG_01_high_F",
        "O_static_AT_F",
        "O_static_AA_F",
        "O_Mortar_01_F"
    ],
    [
        "O_Boat_Armed_01_hmg_F",
        "O_Boat_Transport_01_F"
    ]
]
