[
    "AAF",
    resistance,
    [
        "I_Soldier_F",
        "I_Soldier_LAT_F",
        "I_Soldier_GL_F",
        "I_Soldier_AR_F",
        "I_Soldier_AAR_F",
        "I_Soldier_TL_F",
        "I_Soldier_SL_F",
        "I_Soldier_M_F",
        "I_Soldier_A_F",
        "I_medic_F",
        "I_engineer_F",
        "I_soldier_exp_F",
        "I_Soldier_AT_F",
        "I_Soldier_AAT_F",
        "I_sniper_F",
        "I_spotter_F",
        "I_soldier_repair_F",
        "I_soldier_PG_F",
        "I_helipilot_F",
        "I_helicrew_F",
        "I_crew_F",
        "I_officer_F",
        "I_soldier_UAV_F"
    ],
    [
        "I_Quadbike_01_F",
        "I_MRAP_03_F",
        "I_MRAP_03_hmg_F",
        "I_MRAP_03_gmg_F",
        "I_Truck_02_transport_F",
        "I_Truck_02_covered_F",
        "I_Truck_02_medical_F",
        "I_APC_Wheeled_03_cannon_F",
        "I_APC_tracked_03_cannon_F",
        "I_MBT_03_cannon_F",
        "I_MBT_03_arty_F"
    ],
    [
        "I_UAV_01_F",
        "I_UAV_02_F",
        "I_UGV_01_F",
        "I_UGV_01_rcws_F",
        "I_Heli_light_03_unarmed_F",
        "I_Heli_light_03_F",
        "I_Heli_Transport_02_F",
        "I_Plane_Fighter_03_dynamicLoadout_F"
    ],
    [
        "I_HMG_01_F",
        "I_HMG_01_high_F",
        "I_GMG_01_F",
        "I_GMG_01_high_F",
        "I_static_AT_F",
        "I_static_AA_F",
        "I_Mortar_01_F"
    ],
    [
        "I_Boat_Armed_01_minigun_F",
        "I_Boat_Transport_01_F"
    ]
]
