class Invasion {
    tag = "front";
    class init {
        file = "scripts";
        class initWorld { preInit = 1; };
        class generateSectors { };
        class setupDefenses { };
        class spawnLogisticsMenu { };
        class openBuildMenu { };
        class buildMenu { };
        class buildPurchase { };
        class economyLoop { };
        class aiCommander { };
        class aiTactics { };
        class sideMissions { };
        class selectFactions { };
        class persistenceLoad { };
        class persistenceSave { };
        class persistenceAutoSave { };
        class missionLibrary { };
        class spawnMission { };
        class activateMission { };
        class completeMission { };
        class missionBoard { };
        class enemyAnger { };
        class openMissionBoard { };
        class prisoners { };
        class battleOverlay { };
        class intelMap { };
        class openIntelMap { };
        class shops { };
        class shopMenu { };
        class openShop { };
        class shopPurchase { };
        class privateEconomy { };
        class playerFundsActions { };
        class sectorMonitor { };
        class sectorPresenceClient { };
        class warCrimes { };
        class releaseDetainees { };
        class commandAccess { };
        class registerCommander { };
        class addHCGroup { };
        class flagHighCommandGroup { };
        class spawnPersonalInfantry { };
        class drones { };
        class surrender { };
        class navalOps { };
        class artilleryOps { };
        class repairIndustry { };
        class structureRepairs { };
        class registerFobTruck { };
        class deployFob { };
        class seedFob { };
        class markFob { };
    };
};
