[
    "NATO (Woodland)",
    west,
    [
        "B_Soldier_F",
        "B_soldier_AR_F",
        "B_soldier_LAT_F",
        "B_soldier_GL_F",
        "B_medic_F",
        "B_soldier_AA_F",
        "B_engineer_F"
    ],
    [
        "B_MRAP_01_hmg_F",
        "B_MRAP_01_gmg_F",
        "B_APC_Wheeled_01_cannon_F",
        "B_APC_Tracked_01_rcws_F",
        "B_APC_Tracked_01_AA_F",
        "B_MBT_01_TUSK_F"
    ],
    [
        "B_Heli_Light_01_dynamicLoadout_F",
        "B_Heli_Attack_01_dynamicLoadout_F",
        "B_Heli_Transport_03_F",
        "B_Plane_CAS_01_dynamicLoadout_F",
        "B_Plane_Fighter_01_F"
    ],
    [
        "B_HMG_01_F",
        "B_GMG_01_F",
        "B_static_AT_F",
        "B_static_AA_F"
    ]
]
